import type { Metadata } from "next";
import { SiteShell } from "@/components/site-shell";
import { ClerkProvider } from "@clerk/nextjs";
import { ScrollReveal } from "@/components/scroll-reveal";
import "./globals.css";
import "./overrides.css";
import "./enhancements.css";
import "./people-stage.css";
import "./projects-scroll.css";
import "./article-rich.css";
import "./auth-mobile.css";
import "./admin-queue.css";
import "./admin-ui.css";
import "./motion.css";
import "./header-project.css";
import "./leadership.css";
import "./podcasts.css";
import "./events.css";
import "./footer-fix.css";
import "./content-pages.css";
import "./forum.css";
import "./projects.css";
import "./responsive-fixes.css";
import "./departments-motion.css";
import "./departments-scroll.css";
import "./discussion-page.css";
import "./editorial-redesign.css";
export const metadata: Metadata = { title: "ThinkEconomics", description: "A student-led community for economics, policy, business, and current affairs." };
export default function Layout({ children }: { children: React.ReactNode }) { const enabled = Boolean(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY); const content = <><ScrollReveal/><SiteShell clerkEnabled={enabled}>{children}</SiteShell></>; return <html lang="en"><body>{enabled ? <ClerkProvider>{content}</ClerkProvider> : content}</body></html>; }
