"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { SignInButton, useUser } from "@clerk/nextjs";

type Kind = "comment" | "feedback" | "blog" | "podcast" | "event" | "announcement" | "discussion" | "reply";
type Tab = "feedback" | "blogs" | "podcasts" | "events" | "announcements" | "discussions" | "comments";
type Item = { kind: Kind; id: string; author_name: string; body: string; context: string; created_at: string };
const admins = new Set(["thinkecon@gmail.com", "vyom1907patel@gmail.com"]);
const tabLabels: Record<Tab, string> = { feedback: "Feedback", blogs: "Blogs", podcasts: "Podcasts", events: "Events", announcements: "Announcements", discussions: "Discussion", comments: "Comments" };
const tabKinds: Record<Tab, Kind> = { feedback: "feedback", blogs: "blog", podcasts: "podcast", events: "event", announcements: "announcement", discussions: "discussion", comments: "comment" };

export function AdminPanel({ enabled }: { enabled: boolean }) { return enabled ? <SignedInAdmin /> : <main className="admin-page"><h1>Administration.</h1></main>; }

function SignedInAdmin() {
  const { isLoaded, isSignedIn, user } = useUser();
  const [items, setItems] = useState<Item[]>([]); const [tab, setTab] = useState<Tab>("feedback"); const [error, setError] = useState("");
  const [blog, setBlog] = useState({ title: "", summary: "", body: "" });
  const [announcement, setAnnouncement] = useState({ title: "", summary: "", body: "", cover: "" });
  const [podcast, setPodcast] = useState({ title: "", description: "", videoUrl: "" });
  const [event, setEvent] = useState({ title: "", description: "", body: "", eventDate: "", location: "", imageUrl: "", applicationUrl: "", meetingUrl: "" });
  const [editing, setEditing] = useState<Record<string, string> | null>(null);
  const email = user?.primaryEmailAddress?.emailAddress?.toLowerCase() || ""; const isAdmin = admins.has(email);
  const load = async () => { const response = await fetch("/api/admin"); if (response.ok) setItems(await response.json()); else setError("Could not load administration data."); };
  useEffect(() => { if (isSignedIn && isAdmin) load(); }, [email, isSignedIn]);
  const visible = useMemo(() => items.filter((item) => tab === "discussions" ? item.kind === "discussion" || item.kind === "reply" : item.kind === tabKinds[tab]), [items, tab]);
  const remove = async (item: Item) => { const response = await fetch("/api/admin", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: item.kind, id: item.id }) }); if (response.ok) setItems((current) => current.filter((entry) => entry.id !== item.id)); else setError("Could not delete this item."); };
  const create = async (type: "blog" | "podcast" | "event" | "announcement", payload: Record<string, string>) => { setError(""); const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type, ...payload }) }); if (!response.ok) { setError("Could not create this item."); return; } if (type === "blog") setBlog({ title: "", summary: "", body: "" }); if (type === "announcement") setAnnouncement({ title: "", summary: "", body: "", cover: "" }); if (type === "podcast") setPodcast({ title: "", description: "", videoUrl: "" }); if (type === "event") setEvent({ title: "", description: "", body: "", eventDate: "", location: "", imageUrl: "", applicationUrl: "", meetingUrl: "" }); await load(); };
  const startEdit = async (item: Item) => { setError(""); const response = await fetch(`/api/admin?kind=${item.kind}&id=${item.id}`); if (!response.ok) return setError("Could not load this item."); const data = await response.json(); const fields = Object.fromEntries(Object.entries(data).map(([key, value]) => [key, value == null ? "" : String(value)])); setEditing({ ...fields, kind: item.kind, id: item.id }); };
  const saveEdit = async (form: FormEvent) => { form.preventDefault(); if (!editing) return; const response = await fetch("/api/admin", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); if (!response.ok) return setError("Could not save this item."); setEditing(null); await load(); };
  if (!isLoaded) return <main className="admin-page"><h1>Administration.</h1></main>;
  if (!isSignedIn) return <main className="admin-page"><h1>Administration.</h1><SignInButton mode="modal"><button className="sign-in">Sign in</button></SignInButton></main>;
  if (!isAdmin) return <main className="admin-page"><h1>Administration.</h1><p>This account does not have administration access.</p></main>;
  return <main className="admin-page"><h1>Administration.</h1><nav className="admin-tabs">{(Object.keys(tabLabels) as Tab[]).map((name) => <button key={name} className={tab === name ? "is-active" : ""} onClick={() => setTab(name)}>{tabLabels[name]}</button>)}</nav>
    {tab === "blogs" && <form className="admin-blog-form" onSubmit={(form: FormEvent) => { form.preventDefault(); create("blog", blog); }}><h2>New blog</h2><input required value={blog.title} onChange={(e) => setBlog({ ...blog, title: e.target.value })} placeholder="Blog title"/><input required value={blog.summary} onChange={(e) => setBlog({ ...blog, summary: e.target.value })} placeholder="Short summary"/><textarea required value={blog.body} onChange={(e) => setBlog({ ...blog, body: e.target.value })} placeholder="Write the blog in Markdown"/><button>Create blog</button></form>}
    {tab === "announcements" && <form className="admin-blog-form" onSubmit={(form: FormEvent) => { form.preventDefault(); create("announcement", announcement); }}><h2>New announcement</h2><input required value={announcement.title} onChange={(e) => setAnnouncement({ ...announcement, title: e.target.value })} placeholder="Announcement title"/><input required value={announcement.summary} onChange={(e) => setAnnouncement({ ...announcement, summary: e.target.value })} placeholder="Short summary"/><textarea required value={announcement.body} onChange={(e) => setAnnouncement({ ...announcement, body: e.target.value })} placeholder="Write the announcement in Markdown"/><input value={announcement.cover} onChange={(e) => setAnnouncement({ ...announcement, cover: e.target.value })} placeholder="Cover image URL (optional)"/><button>Create announcement</button></form>}
    {tab === "podcasts" && <form className="admin-blog-form" onSubmit={(form: FormEvent) => { form.preventDefault(); create("podcast", podcast); }}><h2>New podcast</h2><input required value={podcast.title} onChange={(e) => setPodcast({ ...podcast, title: e.target.value })} placeholder="Episode title"/><input required value={podcast.description} onChange={(e) => setPodcast({ ...podcast, description: e.target.value })} placeholder="Episode description"/><input required type="url" value={podcast.videoUrl} onChange={(e) => setPodcast({ ...podcast, videoUrl: e.target.value })} placeholder="YouTube video URL"/><button>Create podcast</button></form>}
    {tab === "events" && <form className="admin-blog-form" onSubmit={(form: FormEvent) => { form.preventDefault(); create("event", event); }}><h2>New event</h2><input required value={event.title} onChange={(e) => setEvent({ ...event, title: e.target.value })} placeholder="Event title"/><input required value={event.description} onChange={(e) => setEvent({ ...event, description: e.target.value })} placeholder="Short description"/><textarea value={event.body} onChange={(e) => setEvent({ ...event, body: e.target.value })} placeholder="Full event details in Markdown"/><input type="date" value={event.eventDate} onChange={(e) => setEvent({ ...event, eventDate: e.target.value })}/><input value={event.location} onChange={(e) => setEvent({ ...event, location: e.target.value })} placeholder="Location"/><input type="url" value={event.imageUrl} onChange={(e) => setEvent({ ...event, imageUrl: e.target.value })} placeholder="Thumbnail image URL"/><input type="url" value={event.applicationUrl} onChange={(e) => setEvent({ ...event, applicationUrl: e.target.value })} placeholder="Application link"/><input type="url" value={event.meetingUrl} onChange={(e) => setEvent({ ...event, meetingUrl: e.target.value })} placeholder="Meeting link"/><button>Create event</button></form>}
    {editing && <form className="admin-blog-form" onSubmit={saveEdit}><h2>Edit {editing.kind}</h2>{!["comment", "feedback", "reply"].includes(editing.kind) && <input required value={editing.title || ""} onChange={(e) => setEditing({ ...editing, title: e.target.value })} placeholder="Title"/>}{editing.summary !== undefined && <input required value={editing.summary} onChange={(e) => setEditing({ ...editing, summary: e.target.value })} placeholder="Short summary"/>}{editing.description !== undefined && <input required value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} placeholder="Description"/>}<textarea required value={editing.body || ""} onChange={(e) => setEditing({ ...editing, body: e.target.value })} placeholder="Content"/>{editing.cover !== undefined && <input value={editing.cover} onChange={(e) => setEditing({ ...editing, cover: e.target.value })} placeholder="Cover image URL"/>}{editing.videoUrl !== undefined && <input required type="url" value={editing.videoUrl} onChange={(e) => setEditing({ ...editing, videoUrl: e.target.value })} placeholder="Video URL"/>}{editing.kind === "event" && <><input type="date" value={editing.eventDate || ""} onChange={(e) => setEditing({ ...editing, eventDate: e.target.value })}/><input value={editing.location || ""} onChange={(e) => setEditing({ ...editing, location: e.target.value })} placeholder="Location"/><input value={editing.imageUrl || ""} onChange={(e) => setEditing({ ...editing, imageUrl: e.target.value })} placeholder="Thumbnail image URL"/><input value={editing.applicationUrl || ""} onChange={(e) => setEditing({ ...editing, applicationUrl: e.target.value })} placeholder="Application link"/><input value={editing.meetingUrl || ""} onChange={(e) => setEditing({ ...editing, meetingUrl: e.target.value })} placeholder="Meeting link"/></>}<button>Save changes</button><button type="button" onClick={() => setEditing(null)}>Cancel</button></form>}
    <section className="admin-queue"><h2>{tabLabels[tab]}</h2>{visible.map((item) => <article key={item.id}><small>{item.context}</small><h3>{item.author_name}</h3><p>{item.body}</p><button onClick={() => startEdit(item)}>Edit</button><button onClick={() => remove(item)}>Delete</button></article>)}{!visible.length && !error && <p>No {tabLabels[tab].toLowerCase()} yet.</p>}{error && <p className="admin-error">{error}</p>}</section>
  </main>;
}
